services:
  database:
    container_name: blockchain-dteti-database
    image: postgres:15-alpine
    restart: unless-stopped
    networks:
      - blockchain-dteti-network
    env_file: .env
    environment:
      TZ: Asia/Jakarta

  backend:
    container_name: blockchain-dteti-backend
    image: blockchain-dteti-backend
    restart: unless-stopped
    networks:
      - blockchain-dteti-network
    env_file: .env
    depends_on:
      - database
    environment:
      TZ: Asia/Jakarta
    expose:
      - "5000"
    ports:
      - target: 5000
        published: 5000

networks:
  blockchain-dteti-network: